# Main Spring Boot configuration file.
# This file contains settings that are common for all environments.
# Environment-specific database settings are placed in:
# - application-local.yml  -> local MySQL on port 3306
# - application-docker.yml -> Docker MySQL on port 3307

spring:
  # Application name used by Spring Boot.
  # It can appear in logs and monitoring tools.
  application:
    name: bank-account-management

  # JPA/Hibernate configuration.
  # Hibernate is used only as ORM here.
  # Flyway is responsible for creating and updating the database schema.
  jpa:
    # validate means:
    # - Hibernate will NOT create or update tables.
    # - Hibernate will only check if the database schema matches the entity mappings.
    # This is the recommended setup when using Flyway migrations.
    hibernate:
      ddl-auto: validate

    # Prints generated SQL statements in the console.
    # Useful during development to see what Hibernate executes.
    show-sql: true
    properties:
      hibernate:
        # Formats SQL in the console output to make it easier to read.
        format_sql: true
        # Hibernate JDBC timezone configuration.
        #
        # In the entities we use Instant for createdOn and modifiedOn.
        # Instant represents an exact moment in time in UTC, for example:
        # 2026-04-30T12:45:10Z
        #
        # This is useful for audit fields such as createdOn, modifiedOn and transfer timestamps,
        # because these fields answer the question: "When exactly did this happen?"
        #
        # LocalDateTime is different. It represents a date and time without timezone information,
        # for example: 2026-04-30T15:45:10.
        # It does not say whether this is Bulgarian time, UTC time, German time, etc.
        #
        # LocalDateTime is more suitable for local business concepts such as appointments,
        # working hours or schedules.
        #
        # For this banking application, Instant is a better choice because account creation,
        # account modification and transfers are exact events in time.
        #
        # Setting the JDBC timezone to UTC helps Hibernate store and read these timestamp values
        # consistently through the JDBC driver.
        jdbc:
          time_zone: UTC

  # Flyway configuration.
  # Flyway executes SQL migration files from src/main/resources/db/migration.
  flyway:
    enabled: true
    # Location where Flyway looks for migration scripts.
    # Example: V1__create_accounts_and_transfers_tables.sql
    locations: classpath:db/migration

# Backend server configuration.
server:
  # The Spring Boot application will run on http://localhost:8080.
  port: 8080