package com.emilyordanov.bankaccountmanagement.account;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA entity mapped to the "accounts" table.
 *
 * This class represents the database table as a Java object.
 * Hibernate does not create the table, because we use Flyway for database migrations.
 *
 * Hibernate only validates the mapping because we configured:
 *
 * spring.jpa.hibernate.ddl-auto=validate
 */
@Entity
@Table(name = "accounts")
@Getter
@Setter
@NoArgsConstructor
public class Account {
    /**
     * Primary key.
     *
     * GenerationType.IDENTITY means the database generates the id.
     * In MySQL this matches BIGINT AUTO_INCREMENT.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Account name.
     *
     * It must be unique according to the assignment.
     *
     * The database also has:
     * CONSTRAINT uk_accounts_name UNIQUE (name)
     */
    @Column(name = "name", nullable = false, unique = true, length = 100)
    private String name;

    /**
     * IBAN of the account.
     *
     * IBAN can be up to 34 characters.
     * It must be unique according to the assignment.
     *
     * The service layer normalizes it by:
     * - removing spaces
     * - converting it to uppercase
     */
    @Column(name = "iban", nullable = false, unique = true, length = 34)
    private String iban;

    /**
     * Current account status.
     *
     * @Enumerated(EnumType.STRING) means the enum is stored as text:
     * ACTIVE / FROZEN
     *
     * This is safer than EnumType.ORDINAL, because ordinal stores numbers.
     * If we later reorder enum values, ordinal mapping can break old data.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private AccountStatus status;

    /**
     * Current available balance.
     *
     * BigDecimal is used for money instead of double/float,
     * because floating-point types can cause precision issues.
     *
     * In the database this maps to DECIMAL(19, 2).
     */
    @Column(name = "available_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal availableAmount;

    /**
     * Creation timestamp.
     *
     * We use Instant because this field represents an exact moment in time.
     * This is suitable for audit fields such as createdOn / modifiedOn
     * and for financial operations.
     */
    @Column(name = "created_on", nullable = false)
    private Instant createdOn;

    /**
     * Last modification timestamp.
     *
     * It can be null for newly created accounts,
     * because the account may not have been modified yet.
     */
    @Column(name = "modified_on")
    private Instant modifiedOn;

    /**
     * Convenience constructor used by the service when creating a new account.
     *
     * We do not pass id, createdOn or modifiedOn manually:
     * - id is generated by the database
     * - createdOn is set by @PrePersist
     * - modifiedOn is set by @PreUpdate
     */
    public Account(String name, String iban, AccountStatus status, BigDecimal availableAmount) {
        this.name = name;
        this.iban = iban;
        this.status = status;
        this.availableAmount = availableAmount;
    }

    /**
     * @PrePersist is a JPA lifecycle callback.
     *
     * It is executed automatically before Hibernate inserts this entity
     * into the database for the first time.
     *
     * We use it to set createdOn automatically.
     *
     * Without this method, we would need to write:
     * account.setCreatedOn(Instant.now());
     *
     * manually in the service every time we create an account.
     */
    @PrePersist
    protected void onCreate() {
        this.createdOn = Instant.now();
    }

    /**
     * @PreUpdate is a JPA lifecycle callback.
     *
     * It is executed automatically before Hibernate updates this entity
     * in the database.
     *
     * We use it to set modifiedOn automatically when:
     * - account is edited
     * - account is frozen
     * - account is unfrozen
     *
     * Important:
     * @PreUpdate is triggered when Hibernate flushes the changes to the database.
     * That is why in the service we use saveAndFlush() for update/freeze/unfreeze,
     * so modifiedOn is updated before we return the response.
     */
    @PreUpdate
    protected void onUpdate() {
        this.modifiedOn = Instant.now();
    }
}
